version: "2"
services:
    app:
      build:
        context: ./
        dockerfile: app.docker
      working_dir: /var/www
      volumes:
      - ./:/var/www
      environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    web:
      build:
        context: ./
        dockerfile: web.docker
      volumes:
      - ./:/var/www
      ports:
      - "8080:80"
      links:
      - app
    database:
      image: mysql:5.6
      volumes:
      - dbdata:/var/lib/mysql
      environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      ports:
      - "3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
      - database:db
      ports:
      - 8000:80
      environment:
        MYSQL_USER: homesteaed
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
volumes:
  dbdata:
